name: Check Test Coverage

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

permissions: read-all

jobs:
  build:
    runs-on: ${{ matrix.os }}

    name: ${{ matrix.os }} (Python ${{ matrix.python-version }})

    strategy:
      matrix:
        os: [ubuntu-latest]
        python-version: ['3.10']

    steps:
      - name: Check out the repository
        uses: actions/checkout@v3

      - name: Install uv and set the python version
        uses: astral-sh/setup-uv@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Sync dependencies
        run: uv sync --all-extras --dev

      - name: Install coverage.py
        run: uv pip install coverage

      - name: Run tests and collect coverage
        run: uv run pytest --cov=wbwdi --cov-report=xml

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v5
        with:
          files: coverage.xml
          token: ${{ secrets.CODECOV_TOKEN }}