name: Test Python Package

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

permissions: read-all

jobs:
  build:
    runs-on: ${{ matrix.os }}

    name: ${{ matrix.os }} (Python ${{ matrix.python-version }})

    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        python-version: ['3.10', '3.11']

    steps:
      - name: Check out the repository
        uses: actions/checkout@v3

      - name: Install uv and set the python version
        uses: astral-sh/setup-uv@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Sync dependencies
        run: uv sync --all-extras --dev

      - name: Run tests
        run: uv run pytest tests